= SMS/MMS 대화방 Protocol
by Shin Kwan Young;

== 전문 (PC/Android -> Server)

PC -> Server 또는 Android -> Server 요청시에는 아래, SMSMMS000 전문 1개만을 사용.

payload 필드에 셋팅할 JSON String 은 아래 기술함

[source, xml]
----
<body name="SMSMMS000">
  <request>
    <field name="payload" type="string"/>
  </request>
</body>
----

== 요청을 위한 JSON Payload 의 기본구조

server 필드는 서버에서 참조하는 정보.

client 필드는 서버에서 참조하지 않고, push payload 생성 시, 그대로 전달하는 payload

client 필드는 Android <-> PC 담당자가 서버와 관계없이 정의 가능함

payload 상의 field 명은 "a-b-c" 와 같이 표기하였으면 합니다.(예) "unread-count"

client 필드 바로 하위의 field 명은, server 바로 하위의 필드명에 없는 것으로 정의해야 함

[source, json]
----
{
  "server": {
    "type": "xxx",
    "receivers": [
      
    ],
    "body-parts": [
      
    ]
  },
  "client": {
         :
         :
  }
}
----


== PC-Originated SMS Sync

■ 요청 : PC -> Server

[source, json]
----
{
  "server": {
    "type": "SYNC_SMS",
    "receivers": [
      {
        "mobile": "010-1111-2222"
      },
      {
        "mobile": "010-3333-4444"
      }
    ]
  },
  "client": {
    "temp-id": "xxxxxx",
    "text": "SMS 문자 내용"
  }
}
----

■ Push Payload : Server -> Android

[source, json]
----
{
  "type": "SYNC_SMS",
  "receivers": [
    {
      "mobile": "010-1111-2222"
    },
    {
      "mobile": "010-3333-4444"
    }
  ],
  "temp-id": "xxxxxx",
  "text": "SMS 문자 내용"
}
----

== Android-Originated SMS Sync 

■ 요청 : Android -> Server

[source, json]
----
{
  "server": {
    "type": "SYNC_SMS",
    "sender-or-receiver": {
      "mobile": "010-1111-2222",
      "name": "홍길동"
    }
  },
  "client": {
    "box" : "IN/OUT",
    "room-id": 222,
    "room-unread-count": 11,
    "message-id": 11,
    "text": "SMS 문자 내용"
  }
}
----

■ Push Payload : Server -> PC

[source, json]
----
{
  "type": "SYNC_SMS",
  "sender-or-receiver": {
    "name": "홍길동",
    "position": "과장",
    "dept-name": "개발1팀",
    "upper-dept-name": "개발실"
  },
  "box": "IN/OUT",
  "room-id": 222,
  "room-unread-count": 11,
  "message-id": 11,
  "text": "SMS 문자 내용"
}
----

== PC-Orginated MMS Sync

■ 요청 : PC -> Server

[source, json]
----
{
  "server": {
    "type": "SYNC_MMS",
    "receivers": [
      {
        "mobile": "010-1111-2222"
      },
      {
        "mobile": "010-3333-4444"
      }
    ],
    "body-parts": [
      {
        "part-id": 1,
        "mime-type": "xxxx/yyyy",
        "text": "MMS 문자 내용",
        "file-id": 1
      },
      {
        "part-id": 2,
        "mime-type": "xxxx/yyyy",
        "text": "MMS 문자 내용",
        "file-id": 2
      }
    ]
  },
  "client": {
    "temp-id": "xxxxxx",
    "subject": "MMS 제목"
  }
}
----
    
■ Push Payload : Server -> Android

[source, json]
----
{
  "type": "OUT_MMS",
  "receivers": [
    {
      "mobile": "010-1111-2222"
    },
    {
      "mobile": "010-3333-4444"
    }
  ],
  "temp-id": "xxxxxx",
  "subject": "MMS 제목",
  "body-parts": [
    {
      "part-id": 1,
      "mime-type": "xxxx/yyyy",
      "text": "MMS 문자 내용",
      "file-url": "http://x.y.z/a/b/c"
    },
    {
      "part-id": 2,
      "mime-type": "xxxx/yyyy",
      "text": "MMS 문자 내용",
      "file-url": "http://x.y.z/a/b/c"
    }
  ]
}
----

== Android-Originated MMS Sync 

■ 요청 : Android -> Server

[source, json]
----
{
  "server": {
    "type": "SYNC_MMS",
    "sender-or-receiver": {
      "mobile": "010-1111-2222",
      "name": "홍길동"
    },
    "body-parts": [
      {
        "part-id": 1,
        "mime-type": "xxxx/yyyy",
        "text": "MMS 문자 내용",
        "file-id": 1
      },
      {
        "part-id": 2,
        "mime-type": "xxxx/yyyy",
        "text": "MMS 문자 내용",
        "file-id": 2
      }
    ]
  },
  "client": {
    "box" : "IN/OUT",
    "room-id": 222,
    "room-unread-count": 11,
    "message-id": 11,
    "subject": "MMS 제목"
  }
}
----

■ Push Payload : Server -> PC

[source, json]
----
{
  "type": "SYNC_MMS",
  "sender-or-receiver": {
    "name": "홍길동",
    "position": "과장",
    "dept-name": "개발1팀",
    "upper-dept-name": "개발실"
  },
  "body-parts": [
    {
      "part-id": 1,
      "mime-type": "xxxx/yyyy",
      "text": "MMS 문자 내용",
      "file-url": "http://x.y.z/a/b/c"
    },
    {
      "part-id": 2,
      "mime-type": "xxxx/yyyy",
      "text": "MMS 문자 내용",
      "file-url": "http://x.y.z/a/b/c"
    }
  ],
  "box" : "IN/OUT",
  "room-id": 222,
  "room-unread-count": 11,
  "message-id": 11,
  "subject": "MMS 제목"
}
----

== PC-Originated SMS/MMS Result

■ 요청 : Android -> Server

[source, json]
----
{
  "server": {
    "type": "SMS_MMS_RESULT",
    "receivers": [
      {
        "mobile": "010-1111-2222",
        "name": "홍길동1"
      },
      {
        "mobile": "010-1111-2223",
        "name": "홍길동2"
      },
      {
        "mobile": "010-1111-2224",
        "name": ""
      }
    ]
  },
  "client": {
    "sub-type": "SMS/MMS",
    "temp-id": "xxxxxx",
    "sms": [
      {
        "receiver": "010-1111-2222",
        "result": true,
        "room-id": 222,
        "message-id": 11,
        "unread-count": 1
      },
      {
        "receiver": "010-1111-2222",
        "result": false,
        "room-id": 223,
        "message-id": 22,
        "unread-count": 1
      }
    ],
    "mms": {
      "result": true,
      "room-id": 222,
      "message-id": 11,
      "unread-count": 11
    }
  }
}
----

■ Push Payload : Server -> PC

[source, json]
----
{
  "type": "SMS_MMS_RESULT",
  "sub-type": "SMS/MMS",
  "temp-id": "xxxxxx",
  "receivers": [
      {
        "mobile" : "010-xxxx-yyyy",
        "name": "이름 또는 전화번호",
        "position": "과장",
        "dept-name": "개발1팀",
        "upper-dept-name": "개발실"
      },
      {
        "mobile" : "010-xxxx-yyyy",
        "name": "이름 또는 전화번호",
        "position": "과장",
        "dept-name": "개발1팀",
        "upper-dept-name": "개발실"
      }
    ],
  "sms": [
    {
      "receiver": "010-1111-2222",
      "result": true,
      "room-id": 222,
      "message-id": 11,
      "unread-count": 1
    },
    {
      "receiver": "010-1111-2222",
        "result": true,
        "room-id": 222,
        "message-id": 11,
        "unread-count": 1
    }
  ],
  "mms": {
    "result": true,
    "room-id": 222,
    "message-id": 11,
    "unread-count": 11
  }
}
----

== Android-Originated SMS/MMS Sync 

■ 요청 : Android -> Server

[source, json]
----
{
  "server": {
    "type": "SYNC_SMS_MMS"
  },
  "client": {
    "sub-type": "READ/ROOM_DEL/MESSAGE_DEL",
    "room-id": 222,
    "room-unread-count": 11,
    "message-id": 11
  }
}
----

■ Push Payload : Server -> PC

[source, json]
----
{
  "type": "SYNC_SMS_MMS",
  "sub-type": "READ/ROOM_DEL/MESSAGE_DEL",
  "room-id": 222,
  "room-unread-count": 11,
  "message-id": 11
}
----

== SMS/MMS 대화방 동기화 ON/OFF 설정 

■ 요청 : Android -> Server

[source, json]
----
{
  "server": {
    "type": "ON_OFF_SMS_MMS",
    "on": true
  }
}
----

■ 응답 : Server -> Android

----
- SMS/MMS 대화방 ON/OFF 설정 요청에 대한 응답결과는 header 의 status 에 설정
- 응답 header의 status 가 0 인 경우에만 UI 상에 On 으로 변경처리

(header.status 정의)

0 : 설정변경 성공
1 : PC가 로그인되어 있지 않음
9998 : Push 실패 
9999 : 알 수 없는 오류
----

■ Push Payload : Server -> PC

Android 의 요청에 의해 Off -> On 또는 On -> Off 로 설정이 변경된 경우 PC 로 Push 됨

[source, json]
----
{
  "type": "ON_OFF_SMS_MMS",
  "on": true
}
----

== SMS/MMS 대화방 On/Off 설정관련 COMM.CMLOGIN01의 응답

로그인이 성공한 경우, COMM.CMLOGIN01 응답전문 body 의 extJsonStr 필드의 JSON 항목에 다음과 같이 제공함

참고) iOS에서 동일계정으로 로그인시, PC로  "ON_OFF_SMS_MMS" push 가 전송됨

[source, json]
----
{
    ..........., 
    "on-off-sms-mms" : true/false, 
    .........
}
----
